config/routes.rb
Rails.application.routes.draw do
  # get '/movies', to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :carts, only: [:create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  resources :directors, shallow: true do
    resources :movies
  end

  resources :movies do
    resources :actors
  end

  resources :users, only: [:show, :new, :create]

  namespace :admin do
    resources :categories, only: [:index]
  end
end

app/models/actor.rb
class Actor < ApplicationRecord

  has_many :actor_movies
  has_many :movies, {through: :actor_movies}
  
end

app/models/actor_movie.rb
class ActorMovie < ApplicationRecord

  belongs_to :actor
  belongs_to :movie

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :cart_contents

  def initialize(cart_contents)
    @cart_contents = cart_contents || {}
  end

  def total_count
    cart_contents.values.sum
  end

  def add_movie(id)
    cart_contents[id.to_s] = (cart_contents[id.to_s] || 0) + 1
  end

  def count_of(id)
    cart_contents[id.to_s]
  end
end

app/models/director.rb
class Director < ApplicationRecord
  validates_presence_of :name
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates_presence_of :title, :description, :director_id
  belongs_to :director
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  enum role: ["default", "admin"]

  validates_uniqueness_of :username
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def set_cart
    @cart ||= Cart.new(session[:cart])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    @movie = Movie.find(params[:movie_id])
    @cart.add_movie(@movie.id)
    session[:cart] = @cart.cart_contents
    flash[:notice] = "You now have #{pluralize(@cart.count_of(@movie.id), @movie.title)} in your cart."
    redirect_to movies_path
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: [:show, :edit, :destroy, :update]

  def index
    @director = Director.all
  end

  def new
    @director = Director.new
  end

  def create
    director = Director.new(director_params)
    if director.save
      redirect_to "/directors/#{director.id}"
    else
      render :new
    end
  end

  def show
    @director = Director.find(params[:id])
    session[:secret] = "This time for real, though."
  end

  private

    def director_params
      params.require(:director).permit(:name)
    end

    def set_director
      @director = Director.find(params[:id])
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @director = Director.find(params[:director_id])
    @movie = Movie.new
  end

  def create
    # movie = Movie.new(movie_params)
    director = Director.find(params[:director_id])
    movie = director.movies.new(movie_params)
    if movie.save
      redirect_to "/movies/#{movie.id}"
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  private

    def movie_params
      params.require(:movie).permit(:title, :description)
    end

    def set_movie
      @movie = Movie.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    # byebug
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You created #{@user.username}!"
      redirect_to user_path(@user)
    else
      render :new
    end
  end

    private

    def user_params
      params.require(:user).permit(:username, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

app/views/directors/new.html.erb
<h3>Create a New Director</h3>

<%= form_for @director do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>

<% end %>

app/views/directors/show.html.erb
<h1><%= @director.id %></h1>
<h3><%= @director.name %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieMania</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
      <% end %>
      <p>Cart: <%= @cart.total_count %></p>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<h1>All Movies</h1>
<% @movies.each do |movie| %>
  <h2> <%= movie.title %> </h2>
  <p> <%= movie.description %> </p>
  <p> <%= movie.director_id %> </p>
  <%= button_to "Add Movie", carts_path(movie_id: movie.id), class: "btn btn-danger" %>
<% end %>

app/views/movies/new.html.erb
<h3>Create a New Movie</h3>

<%= form_for [@director, @movie] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit  %>

<% end %>

app/views/movies/show.html.erb
<h3> <%= @movie.id %>  </h3>
<h2> <%= @movie.title %>  </h2>
<h1> <%= @movie.description %>  </h1>
<h1> <%= @movie.director.name %> </h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= current_user.username %>!</h1>

app/views/welcome/index.html.erb
<%= link_to "Sign Up", new_user_path %>
<%= link_to "Log In", login_path %>